[package]
name = "sifc_vm"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
sifc_err = { path = "../sifc_err" }
sifc_bytecode = { path = "../sifc_bytecode" }
sifc_std = { path = "../sifc_std" }